apiVersion: apps/v1
kind: Deployment
metadata:
  name: argodemo
spec:
  selector:
    matchLabels:
      app: argodemo
  template:
    metadata:
      labels:
        app: argodemo
    spec:
      containers:
      - name: argodemo
        image: argodemo
        ports:
        - containerPort: 8001