apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml

namespace: argodemo

images:
- name: argodemo
<<<<<<< HEAD
  newName: alwaals/argodemo-argocd
  newTag: d755b261e3ba6697c9ce64dbc7ff41d1edb5ed91
=======
  newName: alwaals/argodemo
  newTag: 3359c16b3625d74b7114ecf2909280e8b6e3116b
>>>>>>> 5520397 (updated)
