apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml

namespace: argodemo

images:
- name: argodemo
  newName: alwaals/argodemo-argocd
  newTag: d755b261e3ba6697c9ce64dbc7ff41d1edb5ed91
